blog/urls.py
from django.urls import path, re_path, include
from .views import like_comment, SingleCategory, SinglePost, search_view, SearchResultsView,newpost
from .views import HomeView, AboutView, create_comment,BlogerPostView,post_update
from .api import CommentViewModel
# from .api import post_list, post_detail,comment_list, comment_detail
# from .api import PostView, PostDetailView
# from .api import PostList, PostDetail
# from .api import PostList1, PostDetail1
from .api import PostViewModel,CategoryViewModel,PostSetViewModel
from rest_framework.routers import DefaultRouter
from zoomit.urls import router
# router = DefaultRouter()
router.register(r'posts', PostViewModel)
router.register(r'comments', CommentViewModel)
router.register(r'categories', CategoryViewModel)
router.register(r'settings', PostSetViewModel)


urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    re_path(r'posts/(?P<slug>[-\w]+)/', SinglePost.as_view(), name='post_single'),
    re_path(r'categories/(?P<slug>[-\w]+)/', SingleCategory.as_view(), name='category_single'),
    path('about_us/', AboutView.as_view(), name='about'),
    path('like_comment/', like_comment, name='like_comment'),
    path('comments/', create_comment, name='add_comment'),
    path('searchbar/', SearchResultsView.as_view(), name='searchbar'),
    path('comments/', create_comment, name='add_comment'),
    path('post/create/v1/', newpost, name='new_post'),
    path('post/update/v1/<int:post_id>', post_update, name='update_post'),
    path('post/bloger/<uuid:pk>', BlogerPostView.as_view(), name='bloger_post'),





  
]

zoomit/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework import routers

from account.api import UserViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls')),
                  path('', include('blog.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('api/', include(router.urls)),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.text import slugify





class Category(MPTTModel):
    title = models.CharField(_("Title"), max_length=50)
    slug = models.SlugField(_("Slug"), unique=True, db_index=True, allow_unicode=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['title']
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.slug


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=128)
    promote = models.BooleanField(_('promote'), default=False)
    abstract = models.CharField(_("Abstract"), max_length=130, default='none')
    slug = models.SlugField(_("Slug"), db_index=True, unique=True)
    content = RichTextField(_("Content"), blank=True, null=True)
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    publish_time = models.DateTimeField(_("Publish at"), db_index=True)
    draft = models.BooleanField(_("Draft"), default=True, db_index=True)
    image = models.ImageField(_("image"), upload_to='post/images')
    category = models.ForeignKey(Category, related_name='posts', verbose_name=_(
        "Category"), on_delete=models.SET_NULL, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Author"),
                               related_name='posts', related_query_name='children',
                               on_delete=models.SET_NULL, null=True, blank=True)
    seen = models.PositiveIntegerField(_("seen"),default=0)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ['-publish_time']

    def __str__(self):
        return self.title
        
    def incrementViewCount(self):
        self.seen += 1
        self.save()
        return self.seen

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class PostSetting(models.Model):
    post = models.OneToOneField(
        "Post", verbose_name=_("post"), related_name='post_setting', related_query_name='post_setting',
        on_delete=models.CASCADE)
    comment = models.BooleanField(_("comment"))
    author = models.BooleanField(_("author"))
    allow_discussion = models.BooleanField(_("allow discussion"))

    class Meta:
        verbose_name = _("PostSetting")
        verbose_name_plural = _("PostSettings")


class CommentLike(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    comment = models.ForeignKey('blog.Comment', verbose_name=_(
        'Comment'), related_name='comment_like', related_query_name='comment_like', on_delete=models.CASCADE)
    condition = models.BooleanField(_("Condition"))
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)

    class Meta:
        unique_together = [['author', 'comment']]
        verbose_name = _("CommentLike")
        verbose_name_plural = _("CommentLikes")

    def __str__(self):
        return str(self.condition)


class Comment(models.Model):
    content = models.TextField(_("Content"))
    post = models.ForeignKey(Post, related_name='comments', related_query_name='comments', verbose_name=_(
        "Post"), on_delete=models.CASCADE)
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(_("confirm"), default=False)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-create_at']

    def __str__(self):
        return self.post.title

    @property
    def like_count(self):
        q = CommentLike.objects.filter(comment=self, condition=True)
        return q.count()

    @property
    def dislike_count(self):
        q = self.comment_like.filter(condition=False)
        return q.count()


class RequestAuthor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        "Author_req"),related_query_name='req_author',related_name='req_author', on_delete=models.CASCADE)
    confirm = models.BooleanField(_('confirm req_author'),default=False)
    def __str__(self):
        return self.user.email

blog/views.py
# from django.db.models.query_utils import Q
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models.fields import related
from blog.models import Post
from blog.models import Comment
from django.http import HttpResponse, request
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from .models import CommentLike, Post, Category, PostSetting, RequestAuthor
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.views.generic import TemplateView, DetailView, ListView
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from blog.forms import CommentForm,NewPostForm,NewPostSetForm
import json
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.core.paginator import Paginator


User = get_user_model()


class HomeView(ListView):
    paginate_by = 9
    template_name = 'blog/index.html'
    queryset = Post.objects.filter(draft=False)
    context_object_name = 'posts'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['promote'] = Post.objects.all()
        context['promote1'] = Post.objects.all()[1]
        return context
   


@csrf_exempt
def like_comment(request):
    data = json.loads(request.body)
    user = request.user
    try:
        comment = Comment.objects.get(id=data['comment_id'])
    except Comment.DoesNotExist:
        return HttpResponse('bad request', status=404)
    try:
        comment_like = CommentLike.objects.get(author=user, comment=comment)
        comment_like.condition = data['condition']
        comment_like.save()
    except CommentLike.DoesNotExist:
        CommentLike.objects.create(author=user, condition=data['condition'], comment=comment)
    result = {'like_count': comment.like_count, 'dislike_count': comment.dislike_count}

    return HttpResponse(json.dumps(result), status=201)


@csrf_exempt
def create_comment(request):
    data = json.loads(request.body)

    user = request.user
    try:
        comment = Comment.objects.create(post_id=data['post_id'], content=data['content'], author=user)
        result = {"comment_id": comment.id, "content": comment.content, 'dislike_count': 0, 'like_count': 0,
                  'full_name': user.get_full_name()}
    
        
        return HttpResponse(json.dumps(result), status=201)
    except:
        result = {"error": 'error'}
        return HttpResponse(json.dumps(result), status=401)


class SinglePost(DetailView):
    model = Post
    template_name = 'blog/post_single.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        item = get_object_or_404(Post.objects.select_related('post_setting', 'category', 'author'), slug=slug)
        item.incrementViewCount()
        return item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']
        related_comment = post.comments.filter(post__slug = self.kwargs.get('slug'),is_confirmed=True)
        paginator = Paginator(related_comment, 6) 
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['comments'] = page_obj
        context['settings'] = PostSetting.objects.get(post__slug = self.kwargs.get('slug'))
        context['form'] = CommentForm()
        return context


class SingleCategory(ListView):
    model = Post
    template_name = 'blog/post_archive_class.html'
    context_object_name = 'posts'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.filter(), slug=slug)
        posts = Post.objects.filter(category=category)
        paginator = Paginator(posts, 9)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return page_obj




class AboutView(TemplateView):
    template_name = 'blog/about_us.html'



class SearchResultsView(ListView):
    model = Post
    template_name = 'search/searchbar.html'

    def get_queryset(self):
        query = self.request.GET.get('search')

        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(category__title__icontains=query) | Q(slug__icontains=query)
        )
        return object_list


def search_view(request):
    if request.method == 'GET':
        search = request.GET.get('search')
        post = Post.objects.filter(Q(title__icontains=search))
        context = {'post': post}
        return render(request, 'search/searchbar.html', context)



@login_required(login_url='/accounts/login')
def newpost(request):
    if request.user.is_author or request.user.is_superuser:

        post_form = NewPostForm(initial={'author':request.user})
            

        if request.method == 'POST':
            post_form = NewPostForm(request.POST,request.FILES ,initial={'author':request.user})

            if post_form.is_valid():
            
                new_post= post_form.save(commit=False)
                new_post.author = request.user
                new_post.save()
                PostSetting.objects.create(post_id=new_post.id,comment=True ,author=True ,allow_discussion=True)
                messages.success(request, _('ok you create it !'))
            else:
                messages.warning(request, _('something get wrong'))


        return render(request, 'profiles/new_post_create.html', {'post_form': post_form})
    else:
        raise PermissionDenied()

@login_required(login_url='/accounts/login')
def post_update(request,post_id):
    post = get_object_or_404(Post,id=post_id)

    if post.author.id == request.user.id or request.user.is_superuser:
        post_form = NewPostForm(instance=post)
            

        if request.method == 'POST':
            post_form = NewPostForm(request.POST,request.FILES ,instance=post)

            if post_form.is_valid():

                post_form.save()
                messages.success(request, _('ok you update it !'))
            else:
                messages.warning(request, _('something get wrong'))


        return render(request, 'profiles/new_post_create.html', {'post_form': post_form})
    else :
        raise PermissionDenied()





class BlogerPostView(DetailView):

    template_name = "blog/bloger_posts.html"

    def get_queryset(self) :
        return User.objects.filter(id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bloger_posts = Post.objects.filter(author__id=self.kwargs.get('pk'))
        paginator = Paginator(bloger_posts, 6) 
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context["author"] = User.objects.get(id=self.kwargs.get('pk'))
        context["posts"] = page_obj
        return context
    



# def register_view(request):
#     if request.method == 'POST':
#         user_form = UserThirdRegistrationForm(request.POST)
#         if user_form.is_valid():
#             # Create a new user object but avoid saving it yet
#             new_user = user_form.save(commit=False)
#             # Set the chosen password
#             new_user.set_password(user_form.cleaned_data['password'])
#             # Save the User object
#             new_user.save()
#             return render(request, 'blog/posts.html', {'new_user': new_user})
#
#     else:
#         user_form = UserThirdRegistrationForm()
#     return render(request, 'blog/register.html', {'user_form': user_form})


# def login_view(request):
#     if request.user.is_authenticated:
#         return redirect('posts_archive')
#     if request.method == 'POST':
#         form = UserLoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(request.POST, username=username, password=password)
#             if user and user.is_active:
#                 login(request, user)
#                 return redirect('posts_archive')
#             else:
#                 print('unvalid')
#                 context = {'form': form}
#     else:
#
#         form = UserLoginForm()
#     return render(request, 'blog/login.html', {'form': form})

# def categories_archive(request):
#     categories = Category.objects.all()
#     context = {
#         'categories': categories,
#     }
#     return render(request, 'blog/categories.html', context)


# def category_single(request, pk):
#     try:
#         category = Category.objects.get(slug=pk)
#     except Category.DoesNotExist:
#         raise Http404('Category not found')
#     posts = Post.objects.filter(category=category)
#
#     context = {
#         'posts': posts,
#         'category': category,
#     }
#
#     return render(request, 'blog/post_archive.html', context)


# def single(request, pk):
#     try:
#         post = Post.objects.select_related('post_setting', 'category', 'author').get(slug=pk)
#         categories = Category.objects.all()
#     except Post.DoesNotExist:
#         raise Http404('post not found')
#     context = {
#         'form': CommentForm(),
#         "post": post,
#         'settings': post.post_setting,
#         'category': post.category,
#         'author': post.author,
#         'categories': categories,
#         'comments': post.comments.filter(is_confirmed=True)
#     }
#     if request.method == "POST":
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.author = request.user
#             comment.post = post
#             comment.save()
#         else:

templates/blog/about_us.html
{% extends 'blog/index_base.html' %}
{% load static %}
{% block title %}
    zoomit/about
{% endblock %}

{% block main %}

  



<div id='backy' >
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">

    <div class="col-8 d-flex justify-content-center">

            
            <h1 class="m-5 p-5 text-center">
             <p>وبلاگ نو نویس در سال های بعد از میلاد با توجه </p>
             <p>!به نیاز های روز افزون ملت شریف احداث شد</p>
             </h1>
    

    </div>

    
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">
    <hr class="offset-md">

</div>


{% endblock %}

templates/blog/bloger_posts.html
{% extends 'blog/index_base.html' %}
{% load static %}
{% load filters %}
{% block title %} {{author.full_name}}/posts {% endblock %}

{% block main %}

<div class="container m-5">




 <div style='padding:25px' dir='rtl'>
 <div class="row">
                <ul style='list-style-type:none'>
                    {% if user.avatar %}
                        <li>

                            <img style="width: 120px;height: 120px;margin:30px 0 20px 0"
                                 src="{{ user.avatar.url }}">
                        </li>
                    {% else %}
                        <li>
                            <img style="width: 120px;height: 120px;margin:30px 0 20px 0"
                                 src="https://upload.wikimedia.org/wikipedia/commons/6/67/User_Avatar.png">
                        </li>
                    {% endif %}

                </ul>
                <ul style='list-style-type:none' class='mt-5'>
                        <li><h2>
                        پست های مرتبط با 
                            {{author.full_name}}
                        </h2></li>
                   
                </ul>


    </div>
    </div>


    
    <div></div>





</div>

<div class="container mx-5">
  <div class="row">
    {% for post in posts %}
        <div class="col-lg-4 col-md-6 mb-4 mx-5" style="margin-bottom:20px">
            <div class="card h-100">
                <img class="card-img-top" id="img-posts" src="{{ post.image.url }}" alt="">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'post_single' post.slug %}">{{ post.title }}</a>
                    </h5>

                    <p class="card-text">{{ post.abstract }}</p>

                </div>
                <div class="card-footer">
                    <a href="{% url 'post_single' post.slug %}" class="btn btn-primary">بیشتر بدانید</a>
                    <p class='badge'>{{post.create_at|timesince|convertor}} </p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

    <!-- pagination -->

        {% include 'component/paginate.html' with page_obj=posts %}

    <!-- end pagination -->




{% endblock %}

templates/blog/changepass.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}تغییر رمز عبور{% endblock %}





{% block body %}

    <div class='bg-light m-5 p-5'>
        <h1 class="text-center reg-title">تغییر رمز عبور</h1>
    </div>
   



    {% comment %} <div class='d-flex justify-content-center  m-5 p-5 rounded'>

{% if form.old_password.errors %}<div class='alert alert-danger text-center col-9'>{{ form.old_password.errors }}</div>{% endif %} 
{% if form.new_password1.errors %}<div class='alert alert-danger text-center col-9'>{{ form.new_password1.errors }}</div>{% endif %} 
{% if form.new_password2.errors %}<div class='alert alert-danger text-center col-9'>{{ form.new_password2.errors }}</div>{% endif %}

    </div> {% endcomment %}





    <div class='d-flex justify-content-center m-5 p-5 bg-light rounded'>

                <form method="post" >
                    {% csrf_token %}
                    
                    
                    {{form.old_password|as_crispy_field}}
                    {{form.new_password1|as_crispy_field}}
                    {{form.new_password2|as_crispy_field}}

                    <input type="submit" class="btn btn-outline-primary" value="تغییر رمز عبور">
                </form>
    </div>

{% endblock %}

templates/blog/post_archive_class.html
{% extends 'blog/index_base.html' %}
{% load static %}
{% block title %}
    پست ها با دسته بندی
{% endblock %}


{% block main %}



{% if posts %}
<div class="container " id="parchive-back">
    <div class="row text-center">
        {% for post in posts %}

        <div class="col-lg-4 col-md-6 mb-4 mx-5" style="margin:50px 0 50px 0">
            <div class="card h-100">
                <img class="card-img-top" id="img-posts" src="{{ post.image.url }}" alt="">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'post_single' post.slug %}">{{ post.title }}</a>
                    </h5>

                    <p class="card-text">{{ post.abstract }}</p>

                </div>
                <div class="card-footer">
                    <a href="{% url 'post_single' post.slug %}" class="btn btn-primary">بیشتر بدانید</a>
                    <p class='badge'>{{post.create_at|timesince}} </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

        <!-- pagination -->
        {% include 'component/paginate.html' with page_obj=posts %}
    <!-- end pagination -->
</div>
{% else %}
<div style="width: 400px;height: 400px;margin:0 50px 0 450px; padding:50px; text-align: center;">

    <div class=" bg-warning" style='padding:25px; text-align: center;'><p>فعلا مقاله اي با اين دسته بندي توليد نشده</p></div>
    <div class=""><p><i class="fa fa-3x fa-heartbeat text-danger" aria-hidden="true"> STAY AT HOME</i>
    </p></div>

</div>
{% endif %}



{% endblock %}

templates/blog/post_single.html
{% extends 'blog/index_base.html' %}

{% load static %}
{% load filters %}
{% load jalali_tags %}



{% block title %}
    {{ post.slug }}
{% endblock %}
{% block main %}
    <!-- Page Content -->
    <div class="blog-item" dir='rtl'>


      <img src="{{post.image.url}}" alt={{post.title}} class="hidden-xs" style="height:600px;opacity: 0.7;" />
    	<img src="{{post.image.url}}" alt={{post.title}} class="visible-xs" style="height:200px;opacity: 0.7;" />

      <div class="white">
        <hr class="offset-md">
        <div class="container">
  	    	<div class="row">
  	    		<div class="col-sm-8 col-sm-offset-2">
  	    			<h1 style='margin:10px 0 135px 0'>{{post.title}}</h1>
              <div >
              {{post.content|safe}}
              </div>

  		    		 <button class="btn btn-success btn-sm whatsapp"> <i class="ion-social-whatsapp"></i> Share </button>
  		    		 <button class="btn btn-info btn-sm whatsapp"> <i class="ion-social-twitter"></i> Retweet</button>
  		    		 <button class="btn btn-danger btn-sm whatsapp"> <i class="ion-social-googleplus"></i> Plus </button>
  	    		<p style="padding:35px">
            <p>دسته بندی :<a href="{% url 'category_single' post.category %}" style="" > {{post.category}}</a></p>
            <p>تاریخ انتشار :<a href='#' style="" > {{post.create_at|to_jalali:'%y/%m/%d _ %H:%M:%S'|convertor}}</a></p>
            <p>نویسنده :<a href="{% url 'bloger_post' post.author.id %}" style="" > {{post.author}}</a></p>
            </p>
            </div>
  	    	</div>
      	</div>
        <hr class="offset-lg">
        <hr class="offset-lg">
      </div>
    <hr class="offset-md">

    <hr class="offset-md">

    <!-- comment -->


      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <div class="comments">
              <h2 class="h3">نظرات مقاله</h2>
              <hr class="offset-sm">
              {% if request.user.is_authenticated %}
              <button class="btn btn-default" data-toggle="modal" data-target="#Modal-Comment"> <i class="ion-android-textsms"></i> Add comment </button>
              {% else %}
              <a href="{% url 'login' %}?next={{request.path}}">
              <button class="btn btn-default"> <i class="ion-android-textsms"></i> برای ثبت نظر ابتدا وارد شوید </button>
              </a>
              {% endif %}
              <hr class="offset-md">


            <div class="adds">
            {% for comment in comments %}
            <div>
              <h3>{{comment.author}}</h3>
              <label>{{comment.create_at}}</label>
              <p>
                {{comment.content }}
              </p>

              <p>

                <div>
                    like:<span id='like_counter{{comment.id}}'>{{comment.like_count}}</span>
                    dislike:<span id='dislike_counter{{comment.id}}'>{{comment.dislike_count}}</span>
                </div>

              <i class="ion-close text-success" aria-hidden="true" 
              onclick="likeComment({{comment.id}})"></i>
                <i class="ion-close text-danger" aria-hidden="true"
              onclick="likeComment({{comment.id}},false)"></i>
              </p>
            </div>

            {% endfor %}

            </div>

            

    <!-- pagination -->
        {% include 'component/paginate.html' with page_obj=comments %}
    <!-- end pagination -->



            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- end comment -->



    <!-- comment modal -->

    <div class="modal fade" id="Modal-Comment" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header align-center">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="ion-android-close"></i></span></button>
            <h1 class="h4 modal-title">ثبت نظر</h1>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
            <form class="join"  method="post" id="comment_form">
              <div class="row">
                <div class="col-sm-12">
                       
                    {% csrf_token %}
                    {% include 'component/commentform.html' %}

                    <div class="col-sm-12">
                        <div class="align-right">
                            <hr class="offset-md">
                            <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal"> <i class="ion-android-share"></i> منصرف شدم </button>
                            <button type="submit" class="btn btn-success btn-sm"> <i class="ion-android-send"></i> ثبت کن</button>
                            <hr class="offset-md">
                        </div>
                    </div>
                        
                </div>



              </div>
             </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end comm modal -->




{% endblock %}


{% block javascript %}
    <script>
        function likeComment(commentID, condition = true) {
            const data = JSON.stringify({comment_id: commentID, condition})
            console.log(data)
            $.ajax({
                type: "POST",
                url: "{% url 'like_comment' %}",
                data: data,
                success: function (response) {
                    const data = JSON.parse(response)
                    $(`#like_counter${commentID}`).text(data.like_count)
                    $(`#dislike_counter${commentID}`).text(data.dislike_count)
                }
            });
        }
    </script>









    <script>
        document.getElementById("comment_form").addEventListener("submit", function (event) {
            event.preventDefault();
            const content = $('#id_content').val()
            const data = JSON.stringify({ content , post_id:{{post.id}} })


            request= $.ajax({
                type: "post",
                url: "{% url 'add_comment' %}",
                data: data,
            
            });

            request.done(function( msg ) {
                

                Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'دیدگاه شما دریافت شد بعد از بررسی ثبت می شود!',
                showConfirmButton: false,
                timer: 2500
                })
            });


            request.fail(function( jqXHR, textStatus ) {
            alert( "Request failed: " + textStatus );
            });

        }, false);
    </script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}